[options]
admin_passwd = $pbkdf2-sha512$600000$JORci3GO8d67l9Kas/aeUw$1iZtSfjzRsF.GlNN4sQpWh5y75Nb/Qbaw1HeOgV1g6wJhywWvKa9RlEoCdu/T3nL3Jt6rI9ZzeGnu0q./ENzdg
db_host = localhost
db_port = 5432
db_user = odoo19
db_password = cool
addons_path = /home/cybrosys/odoo19/addons,/home/cybrosys/odoo19/custom_addons
http_port = 8019

