from . import hotel_rooms
from . import room_facility
from . import food_items
from . import food_category
from . import hotel_accommodation
from . import order_food
from . import accommodation_guests_lines
from . import food_order_lines
from . import payment_lines
from . import res_partner
from . import hotel_image
from . import res_config_settings
from . import website_cart